// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20200607081705_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.MemberEntity", b =>
                {
                    b.Property<int>("m_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("m_no")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("fixedCost")
                        .HasColumnName("fixedCost")
                        .HasColumnType("text");

                    b.Property<DateTime>("intime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("monthlyIncome")
                        .HasColumnName("monthlyIncome")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<string>("savings")
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .HasColumnType("text");

                    b.Property<DateTime>("utime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("m_no");

                    b.ToTable("member");
                });

            modelBuilder.Entity("Entities.MemberEntity", b =>
                {
                    b.OwnsOne("Valueobject.Member.AmountLimitValueObject", "amountLimit", b1 =>
                        {
                            b1.Property<int>("MemberEntitym_no")
                                .HasColumnType("integer");

                            b1.Property<int>("_amountLimit")
                                .HasColumnType("integer");

                            b1.HasKey("MemberEntitym_no");

                            b1.ToTable("member");

                            b1.WithOwner()
                                .HasForeignKey("MemberEntitym_no");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
