-- Table: public.member

-- DROP TABLE public.member;

CREATE TABLE public.member
(
    m_no integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "userName" text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    "monthlyIncome" text COLLATE pg_catalog."default",
    savings text COLLATE pg_catalog."default",
    "fixedCost" text COLLATE pg_catalog."default",
    intime timestamp without time zone NOT NULL,
    utime timestamp without time zone NOT NULL,
    "amountLimit__amountLimit" integer,
    "saltPassword" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_member" PRIMARY KEY (m_no)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.member
    OWNER to postgres;