-- Table: public.books

-- DROP TABLE public.books;

CREATE TABLE public.books
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    m_no text COLLATE pg_catalog."default",
    "registDate__registDate" timestamp without time zone,
    "amountUsed" integer NOT NULL,
    intime timestamp without time zone NOT NULL,
    utime timestamp without time zone NOT NULL,
    CONSTRAINT "PK_books" PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.books
    OWNER to postgres;