version: '3'
services:
  Core:
    build: ./
    image: aspnetapp:Core
    container_name: sdp
    ports:
      - 443:443
    environment:
      - ConnString
  postgres:
    container_name: my-postgres
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGPASSWORD
      - POSTGRES_DB
      - DATABASE_HOST
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d